#cloud-config
package_update: true
package_upgrade: true
packages:
  - make
  - nfs-utils
  - rpm-build
  - tmux
runcmd:
  - yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
  - yum install -y http://mirror.centos.org/centos/8/PowerTools/x86_64/os/Packages/lua-filesystem-1.6.3-7.el8.x86_64.rpm
  - yum install -y http://mirror.centos.org/centos/8/PowerTools/x86_64/os/Packages/lua-posix-33.3.1-9.el8.x86_64.rpm
  - yum install -y Lmod
  - mkdir -p /opt/pkgs
  - cd /opt/pkgs
  - mkdir efs
  - cd efs
  - git clone https://github.com/aws/efs-utils.git efs
  - cd efs-utils
  - make rpm
  - yum -y install build/amazon-efs-utils*rpm
  - file_system_ip_1=10.0.1.169
  - efs_mount_point_1=/data
  - mkdir -p "${efs_mount_point_1}"
  - test -f "/sbin/mount.efs" && printf "\n${file_system_ip_1}:/ ${efs_mount_point_1} nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,_netdev 0 0\n" >> /etc/fstab
  - test -f "/sbin/mount.efs" && grep -ozP 'client-info]\nsource' '/etc/amazon/efs/efs-utils.conf'; if [[ $? == 1 ]]; then printf "\n[client-info]\nsource=liw\n" >> /etc/amazon/efs/efs-utils.conf; fi;
  - retryCnt=15; waitTime=30; while true; do mount -a -t efs,nfs4 defaults; if [ $? = 0 ] || [ $retryCnt -lt 1 ]; then echo File system mounted successfully; break; fi; echo File system not available, retrying to mount.; ((retryCnt--)); sleep $waitTime; done;
